version: '3'
services:

  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: hh_bot
    image: hh_bot
    restart: unless-stopped
    environment:
      MONGODB_DATABASE: hh_bot
      MONGODB_USERNAME: user1
      MONGODB_PASSWORD: passw1
#      MONGODB_HOSTNAME: mongodb
      MONGODB_HOSTNAME: mongodb+srv://alex:alcatell@cluster0.pjnfg.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      TOKEN: 6914689569:AAGCja0jmasA8oy_BtzG3YTPjwquKJ3VWlE
    volumes:
      - appdata:/var/www/
#    depends_on:
#      - mongodb
    networks:
      - frontend
      - backend

#  mongodb:
#    image: mongo:6.0.6
#    container_name: mongo_db
#    restart: unless-stopped
#    command: mongod --auth
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongodbuser
#      MONGO_INITDB_ROOT_PASSWORD: passw1
#      MONGO_INITDB_DATABASE: hh_bot
#      MONGODB_DATA_DIR: /data/db
#      MONDODB_LOG_DIR: /dev/null
#    ports:
#      - "27117:27017"
#    volumes:
#      - mongodbdata:/data/db
#    networks:
#      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
